apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: hello-world-app
  namespace: hello-world
spec: 
  destination: 
    namespace: hello-world
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbookexample-1/hello-world
    repoURL: "https://github.com/YordanAsenov/argocd-hello-world.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true